In [1]:
#importamos librerias 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
#cargar archivo csv
df=pd.read_csv('Victoria_limpio.csv')
#eliminamos la columna unnamed 
df= df.drop(['Unnamed: 0'], axis=1)
df.head(5)

listing_url                              name  \
0   https://www.airbnb.com/rooms/19898                     Duchess Suite   
1   https://www.airbnb.com/rooms/83515                 GALLERY B&B SUITE   
2  https://www.airbnb.com/rooms/168460     Perfectly located lovely home   
3  https://www.airbnb.com/rooms/185732  Romantic 2 bedroom private suite   
4  https://www.airbnb.com/rooms/193366                     Tudor Cottage   

                                         description  \
0                      No se proporciona descripción   
1  A quiet and sunny suite with a private entranc...   
2  Wonderful neighborhood, two blocks to inner ha...   
3  The unit is a 2 bedroom suite sectioned off fr...   
4  In the historic Rockland area of Victoria, thi...   

                               neighborhood_overview  \
0                        No se proporcionan detalles   
1  Our property has gardens, an orchard, a pond a...   
2  Lovely neighborhood with friendly neighbors su...   
3                        No se proporcionan detalles   
4  We are surrounded by heritage homes with lovel...   

                                         picture_url host_name  host_since  \
0  https://a0.muscache.com/pictures/101822/ae950f...      Ryan  2010-01-11   
1  https://a0.muscache.com/pictures/6110737/930db...     Celia  2011-03-21   
2  https://a0.muscache.com/pictures/7a2bfc51-fd59...   Deborah  2011-07-10   
3  https://a0.muscache.com/pictures/20829630/9356...     Peter  2011-07-27   
4  https://a0.muscache.com/pictures/6145514/1eb8d...    Sandra  2011-08-07   

   host_response_time host_response_rate host_is_superhost  ...  \
0         Desconocido                 -%                 f  ...   
1      within an hour               100%                 t  ...   
2         Desconocido                 -%                 f  ...   
3  a few days or more                10%                 f  ...   
4  within a few hours                75%                 f  ...   

  review_scores_cleanliness review_scores_checkin review_scores_communication  \
0                      5.00                  5.00                        5.00   
1                      4.87                  4.92                        4.84   
2                      4.98                  4.89                        4.92   
3                      4.65                  4.82                        4.88   
4                      4.78                  4.92                        4.89   

  review_scores_location review_scores_value calculated_host_listings_count  \
0                   4.90                4.80                            1.0   
1                   4.94                4.75                            2.0   
2                   5.00                4.90                            1.0   
3                   4.90                4.61                            3.0   
4                   4.88                4.76                            1.0   

  calculated_host_listings_count_entire_homes  \
0                                         0.0   
1                                         2.0   
2                                         1.0   
3                                         0.0   
4                                         1.0   

  calculated_host_listings_count_private_rooms  \
0                                          0.0   
1                                          0.0   
2                                          0.0   
3                                          0.0   
4                                          0.0   

  calculated_host_listings_count_shared_rooms reviews_per_month  
0                                         0.0              1.90  
1                                         0.0              0.90  
2                                         0.0              0.43  
3                                         0.0              0.32  
4                                         0.0              1.01  

[5 rows x 50 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3967 entries, 0 to 3966
Data columns (total 50 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   listing_url                                   3967 non-null   object 
 1   name                                          3967 non-null   object 
 2   description                                   3967 non-null   object 
 3   neighborhood_overview                         3967 non-null   object 
 4   picture_url                                   3967 non-null   object 
 5   host_name                                     3967 non-null   object 
 6   host_since                                    3967 non-null   object 
 7   host_response_time                            3967 non-null   object 
 8   host_response_rate                            3967 non-null   object 
 9   host_is_superhost                             3967 non-null   o

In [4]:
f1=df.iloc[ :  , [8,9,10,13,14,20,21,24,25,26,28,40,44,45,49] ]
f1

host_response_rate host_is_superhost host_identity_verified  \
0                    -%                 f                      f   
1                  100%                 t                      t   
2                    -%                 f                      f   
3                   10%                 f                      t   
4                   75%                 f                      t   
...                 ...               ...                    ...   
3962               100%                 f                      t   
3963                 -%                 f                      t   
3964                 -%                 f                      f   
3965                 -%                 f                      t   
3966                 -%                 f                      t   

                    property_type        room_type instant_bookable  \
0     Private room in rental unit     Private room                f   
1              Entire guest suite  Entire home/apt                t   
2                Entire townhouse  Entire home/apt                f   
3            Private room in home     Private room                f   
4              Entire guest suite  Entire home/apt                t   
...                           ...              ...              ...   
3962           Entire rental unit  Entire home/apt                t   
3963                  Entire home  Entire home/apt                f   
3964            Entire guesthouse  Entire home/apt                f   
3965                  Entire home  Entire home/apt                f   
3966           Entire rental unit  Entire home/apt                f   

                       id  accommodates  bathrooms  bedrooms  price  \
0                   19898           1.0        1.0       1.0  188.5   
1                   83515           2.0        1.0       1.0  175.0   
2                  168460           3.0        1.0       2.0  200.0   
3                  185732           5.0        1.0       2.0  199.0   
4                  193366           6.0        1.0       2.0  135.0   
...                   ...           ...        ...       ...    ...   
3962  1297151447049091869           4.0        1.0       1.0  178.0   
3963  1297951442048266188           4.0        1.0       1.0  242.0   
3964  1298057658412712726           4.0        1.0       2.0  155.5   
3965  1298245712044358317           4.0        1.0       1.0  242.0   
3966  1298767818701196083           4.0        1.0       2.0  300.0   

      review_scores_cleanliness  review_scores_value  \
0                          5.00                 4.80   
1                          4.87                 4.75   
2                          4.98                 4.90   
3                          4.65                 4.61   
4                          4.78                 4.76   
...                         ...                  ...   
3962                       5.00                 4.80   
3963                       5.00                 4.80   
3964                       5.00                 4.80   
3965                       5.00                 4.80   
3966                       5.00                 4.80   

      calculated_host_listings_count  reviews_per_month  
0                                1.0               1.90  
1                                2.0               0.90  
2                                1.0               0.43  
3                                3.0               0.32  
4                                1.0               1.01  
...                              ...                ...  
3962                             1.0               1.90  
3963                             2.0               1.90  
3964                             1.0               1.90  
3965                             2.0               1.90  
3966                             1.0               1.90  

[3967 rows x 15 columns]

In [5]:
f1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3967 entries, 0 to 3966
Data columns (total 15 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   host_response_rate              3967 non-null   object 
 1   host_is_superhost               3967 non-null   object 
 2   host_identity_verified          3967 non-null   object 
 3   property_type                   3967 non-null   object 
 4   room_type                       3967 non-null   object 
 5   instant_bookable                3967 non-null   object 
 6   id                              3967 non-null   int64  
 7   accommodates                    3967 non-null   float64
 8   bathrooms                       3967 non-null   float64
 9   bedrooms                        3967 non-null   float64
 10  price                           3967 non-null   float64
 11  review_scores_cleanliness       3967 non-null   float64
 12  review_scores_value             39

In [6]:
#convertimos las variables de tipo object a tipo numérico 
#convertimos string a tipos numéricos
f1['host_is_superhost'] = f1['host_is_superhost'].replace({'f': 0, 't': 1})
f1['host_identity_verified'] = f1['host_identity_verified'].replace({'f': 0, 't': 1})
f1['instant_bookable'] = f1['instant_bookable'].replace({'f': 0, 't': 1})

#from sklearn.preprocessing import LabelEncoder

#encoder = LabelEncoder()
#df['property_type'] = encoder.fit_transform(df['property_type'])

#from sklearn.preprocessing import LabelEncoder

#encoder = LabelEncoder()
#f1['property_type'] = encoder.fit_transform(f1['property_type'])
#f1['property_type'] = f1['property_type'].astype(float)

frecuencias = f1['property_type'].value_counts()
f1['property_type'] = f1['property_type'].map(frecuencias)
#print(f1[['property_type']])


f1['host_response_rate'] = f1['host_response_rate'].astype(str).str.rstrip('%')
f1['host_response_rate'] = pd.to_numeric(f1['host_response_rate'], errors='coerce').fillna(0)

f1['room_type'] = f1['room_type'].map({
    'Entire home/apt': 1,
    'Private room': 2,
    'Shared room': 3,
    'Hotel room': 4
})

f1['price'] = f1['price'].astype(str).str.rstrip('$')
f1['price'] = pd.to_numeric(f1['price'], errors='coerce').fillna(0)

C:\Users\josse\AppData\Local\Temp\ipykernel_1328\2464637102.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  f1['host_is_superhost'] = f1['host_is_superhost'].replace({'f': 0, 't': 1})
C:\Users\josse\AppData\Local\Temp\ipykernel_1328\2464637102.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f1['host_is_superhost'] = f1['host_is_superhost'].replace({'f': 0, 't': 1})
C:\Users\josse\AppData\Local\Temp\ipykernel_1328\2464637102.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed

**DECLARACIÓN DE VARIABLES DEPENDIENTES E INDEPENDIENTES**

In [62]:
print(f1[['property_type']])

      property_type
0                16
1               884
2                43
3               298
4               884
...             ...
3962            345
3963            909
3964            188
3965            909
3966            345

[3967 rows x 1 columns]


In [64]:
frecuencias

property_type
Entire home                           909
Entire guest suite                    884
Entire condo                          410
Entire rental unit                    345
Private room in home                  298
                                     ... 
Shared room in guest suite              1
Campsite                                1
Private room in religious building      1
Shared room in condo                    1
Shared room in rental unit              1
Name: count, Length: 62, dtype: int64

In [7]:
#declaración de las variables independientes que se van a comparar con cada variable independiente 
Vars_Indep= f1[['host_response_rate', 'host_is_superhost', 'room_type', 'host_identity_verified', 'property_type', 'instant_bookable', 'instant_bookable', 'bathrooms']]


In [8]:
#Declaración de variables dependientes
Var_Dep= f1['id']
Var_Dep2= f1['host_response_rate']
Var_Dep3= f1['host_is_superhost']
Var_Dep4= f1['calculated_host_listings_count']
Var_Dep5= f1['room_type']
Var_Dep6= f1['accommodates']
Var_Dep7= f1['bedrooms']
Var_Dep8= f1['price']
Var_Dep9= f1['review_scores_value']
Var_Dep10= f1['reviews_per_month']

In [9]:
#Se define model como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()
model2=LinearRegression()
model3= LinearRegression()
model4=LinearRegression()
model5= LinearRegression()
model6=LinearRegression()
model7= LinearRegression()
model8=LinearRegression()
model9= LinearRegression()
model10=LinearRegression()

In [10]:
#Verificamos la función relacionada al modelo
type(model)
type(model2)
type(model3)
type(model4)
type(model5)
type(model6)
type(model7)
type(model8)
type(model9)
type(model10)

sklearn.linear_model._base.LinearRegression

In [11]:
#Ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)
model2.fit(X=Vars_Indep, y=Var_Dep2)
model3.fit(X=Vars_Indep, y=Var_Dep3)
model4.fit(X=Vars_Indep, y=Var_Dep4)
model5.fit(X=Vars_Indep, y=Var_Dep5)
model6.fit(X=Vars_Indep, y=Var_Dep6)
model7.fit(X=Vars_Indep, y=Var_Dep7)
model8.fit(X=Vars_Indep, y=Var_Dep8)
model9.fit(X=Vars_Indep, y=Var_Dep9)
model10.fit(X=Vars_Indep, y=Var_Dep10)

LinearRegression()

In [12]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([ 1.89883517e+15, -1.58185850e+17,  2.32685117e+16, -1.08993291e+17,
         1.21551983e+14,  7.55081553e+15,  7.55081553e+15,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(4.256801084334849e+17)}

**Modelo matemático: y= 1.88341490e+15 + -1.57610566e+17 +-1.36480330e+17 + -1.04772873e+17 + 5.06801366e+15 + 2.14682284e+15 + 2.14682284e+15 + 0.00000000e+00 + 5.832595018560591e+17**

In [13]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model.score(Vars_Indep,Var_Dep)

0.039118932483879876

In [14]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model2.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([ 1.00000000e+00, -8.04525734e-16, -5.25851195e-14,  1.20943725e-13,
         3.43384377e-17,  5.66608457e-15,  5.66608457e-15,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(-1.4637180356658064e-12)}

In [15]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model2.score(Vars_Indep,Var_Dep2)

1.0

In [16]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model3.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([-8.16859625e-18,  1.00000000e+00,  1.77581796e-13, -2.21948999e-15,
         2.42959553e-16,  8.76937757e-16, -9.27174658e-16,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(-3.3495428652940973e-13)}

In [17]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model3.score(Vars_Indep,Var_Dep3)

1.0

In [18]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model4.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([ 3.63272294e-03, -2.36589254e-02,  5.42899011e-01,  1.05361303e-01,
        -2.82485072e-04,  1.85984528e-01,  1.85984528e-01,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(0.6626589906813845)}

In [19]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model4.score(Vars_Indep,Var_Dep4)

0.11881620118897906

In [20]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model5.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([ 4.38421758e-18, -7.46256355e-16,  1.00000000e+00, -7.49122262e-16,
         1.19668435e-17,  2.76060380e-15, -2.56846672e-15,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(8.659739592076221e-15)}

In [21]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model5.score(Vars_Indep,Var_Dep5)

1.0

In [22]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model6.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([ 9.73763161e-04, -2.48122221e-01, -1.32149431e+00,  2.25010037e-01,
         4.09328708e-04,  1.35224481e-01,  1.35224481e-01,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(4.658864678348202)}

In [23]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model6.score(Vars_Indep,Var_Dep6)

0.1166735566958097

In [24]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model7.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([-3.51725723e-04, -8.97592964e-02, -2.96071859e-01,  1.45990788e-01,
         2.54463936e-04,  7.02331168e-04,  7.02331168e-04,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(1.577109097278981)}

In [25]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model7.score(Vars_Indep,Var_Dep7)

0.05969235115591642

In [26]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model8.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([-2.04280224e-01,  2.15331576e+00, -4.19151249e+01,  5.75662641e+00,
        -1.29786479e-02,  4.21544896e+00,  4.21544896e+00,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(218.5127235639036)}

In [27]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model8.score(Vars_Indep,Var_Dep8)

0.08098369541557104

In [28]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model9.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([-1.24207706e-04,  3.39864566e-02, -7.89681346e-03, -1.34658447e-02,
         3.29078330e-05, -1.19198956e-02, -1.19198956e-02,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(4.821322513574154)}

In [29]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model9.score(Vars_Indep,Var_Dep9)

0.036702722613694116

In [30]:
#verificamos los coeficientes obtenidos para el modelo ajustado 
model10.__dict__

{'fit_intercept': True,
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['host_response_rate', 'host_is_superhost', 'room_type',
        'host_identity_verified', 'property_type', 'instant_bookable',
        'instant_bookable', 'bathrooms'], dtype=object),
 'n_features_in_': 8,
 'coef_': array([ 2.79241265e-03,  5.54298890e-01, -2.52093413e-01, -7.60088891e-02,
         4.12854458e-05, -1.54416604e-02, -1.54416604e-02,  0.00000000e+00]),
 'rank_': 6,
 'singular_': array([2.22257910e+04, 2.51484269e+03, 3.80569697e+01, 2.93055173e+01,
        2.10544455e+01, 1.66829296e+01, 5.89993733e-14, 0.00000000e+00]),
 'intercept_': np.float64(1.3771784020693367)}

**Modelo matemático: y= 2.78938456e-03 + 5.53593527e-01 + -2.61858104e-01 + -7.51179183e-02 + 3.36057982e-04 + -1.61960510e-02 + -1.61960510e-02 + 0.00000000e+00 + 1.4164638948616772**

In [31]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R Determinación
model10.score(Vars_Indep,Var_Dep10)

0.09110951437551351

In [32]:
#Predecimos los valores a partir de las variables independientes 
y_pred= model.predict(X=Vars_Indep)
y_pred

array([4.74161964e+17, 4.94206579e+17, 4.54175355e+17, ...,
       4.71800393e+17, 4.50446081e+17, 3.81890763e+17], shape=(3967,))

In [33]:
#Predecimos los valores a partir de las variables independientes 
y_pred2= model2.predict(X=Vars_Indep)
y_pred2

array([-1.56833886e-12,  1.00000000e+02, -1.51482660e-12, ...,
       -1.50984753e-12, -1.36414579e-12, -1.38351267e-12], shape=(3967,))

In [34]:
#Predecimos los valores a partir de las variables independientes 
y_pred3= model3.predict(X=Vars_Indep)
y_pred3

array([ 2.40966583e-14,  1.00000000e+00, -1.46925230e-13, ...,
       -1.11696095e-13,  6.12582531e-14, -7.57709347e-14], shape=(3967,))

In [35]:
#Predecimos los valores a partir de las variables independientes 
y_pred4= model4.predict(X=Vars_Indep)
y_pred4

array([1.74393725, 1.77278493, 1.19341114, ..., 1.15245081, 1.05414038,
       1.21346196], shape=(3967,))

In [36]:
#Predecimos los valores a partir de las variables independientes 
y_pred5= model5.predict(X=Vars_Indep)
y_pred5

array([2., 1., 1., ..., 1., 1., 1.], shape=(3967,))

In [37]:
#Predecimos los valores a partir de las variables independientes 
y_pred6= model6.predict(X=Vars_Indep)
y_pred6

array([2.02242531, 4.04393003, 3.3549715 , ..., 3.41432416, 3.9344602 ,
       3.7035988 ], shape=(3967,))

In [38]:
#Predecimos los valores a partir de las variables independientes 
y_pred7= model7.predict(X=Vars_Indep)
y_pred7

array([0.9890368 , 1.52844694, 1.29197919, ..., 1.32887646, 1.65833574,
       1.51481808], shape=(3967,))

In [39]:
#Predecimos los valores a partir de las variables independientes 
y_pred8= model8.predict(X=Vars_Indep)
y_pred8

array([134.47481543, 161.03729169, 176.03951682, ..., 174.15761288,
       170.55663418, 177.87659157], shape=(3967,))

In [40]:
#Predecimos los valores a partir de las variables independientes 
y_pred9= model9.predict(X=Vars_Indep)
y_pred9

array([4.80605541, 4.82677627, 4.81484074, ..., 4.81961237, 4.82987308,
       4.81131306], shape=(3967,))

In [41]:
#Predecimos los valores a partir de las variables independientes 
y_pred10= model10.predict(X=Vars_Indep)
y_pred10

array([0.87365214, 1.88822927, 1.12686026, ..., 1.13284665, 1.08660457,
       1.06331958], shape=(3967,))

**DETERMINAMOS COEFICIENTES DE DETERMINACIÓN**

In [42]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter=model.score(X=Vars_Indep, y=Var_Dep)
coef_Deter

0.039118932483879876

In [43]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter2=model2.score(X=Vars_Indep, y=Var_Dep2)
coef_Deter2

1.0

In [44]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter3=model3.score(X=Vars_Indep, y=Var_Dep3)
coef_Deter3

1.0

In [45]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter4=model4.score(X=Vars_Indep, y=Var_Dep4)
coef_Deter4

0.11881620118897906

In [46]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter5=model5.score(X=Vars_Indep, y=Var_Dep5)
coef_Deter5

1.0

In [47]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter6=model6.score(X=Vars_Indep, y=Var_Dep6)
coef_Deter6

0.1166735566958097

In [48]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter7=model7.score(X=Vars_Indep, y=Var_Dep7)
coef_Deter7

0.05969235115591642

In [49]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter8=model8.score(X=Vars_Indep, y=Var_Dep8)
coef_Deter8

0.08098369541557104

In [50]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter9=model9.score(X=Vars_Indep, y=Var_Dep9)
coef_Deter9

0.036702722613694116

In [51]:
#Corroboramos cual es el coeficiente de Determinación de nuestro modelo
coef_Deter10=model10.score(X=Vars_Indep, y=Var_Dep10)
coef_Deter10

0.09110951437551351

In [52]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl=np.sqrt(coef_Deter)
coef_Correl

np.float64(0.19778506638237345)

In [53]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl2=np.sqrt(coef_Deter2)
coef_Correl2

np.float64(1.0)

In [54]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl3=np.sqrt(coef_Deter3)
coef_Correl3

np.float64(1.0)

In [55]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl4=np.sqrt(coef_Deter4)
coef_Correl4

np.float64(0.344697260199409)

In [56]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl5=np.sqrt(coef_Deter5)
coef_Correl5

np.float64(1.0)

In [57]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl6=np.sqrt(coef_Deter6)
coef_Correl6

np.float64(0.3415751113529932)

In [58]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl7=np.sqrt(coef_Deter7)
coef_Correl7

np.float64(0.24432018163859576)

In [59]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl8=np.sqrt(coef_Deter8)
coef_Correl8

np.float64(0.2845763437384967)

In [60]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl9=np.sqrt(coef_Deter9)
coef_Correl9

np.float64(0.19157954643879424)

In [61]:
#Corroboramos cual es el coeficiente de Correlación de nuestro modelo
coef_Correl10=np.sqrt(coef_Deter10)
coef_Correl10

np.float64(0.3018435263104271)